import XCTest
import FT8Engine

final class AdifTests: XCTestCase {

    private func rec(
        id: Int64? = nil,
        call: String,
        gridsquare: String = "",
        mode: String = "",
        rstSent: String = "",
        rstRcvd: String = "",
        qsoDate: String = "",
        timeOn: String = "",
        qsoDateOff: String = "",
        timeOff: String = "",
        band: String = "",
        freq: String = "",
        stationCallsign: String = "",
        myGridsquare: String = "",
        comment: String = ""
    ) -> QsoRecord {
        QsoRecord(id: id, call: call, gridsquare: gridsquare, mode: mode, rstSent: rstSent,
                  rstRcvd: rstRcvd, qsoDate: qsoDate, timeOn: timeOn, qsoDateOff: qsoDateOff,
                  timeOff: timeOff, band: band, freq: freq, stationCallsign: stationCallsign,
                  myGridsquare: myGridsquare, comment: comment)
    }

    // MARK: export

    func testExportMatchesDesktopFormatByteForByte() {
        let r = rec(id: 7, call: "K1ABC", gridsquare: "FN42", mode: "FT8", rstSent: "-08",
                    rstRcvd: "-12", qsoDate: "20231114", timeOn: "221320", qsoDateOff: "20231114",
                    timeOff: "221520", band: "20m", freq: "14.074", stationCallsign: "K0XYZ",
                    myGridsquare: "EN37", comment: "")
        let expected =
            "FT8AF ADIF Export<eoh>\n"
            + "<call:5>K1ABC "
            + "<QSL_RCVD:1>N "
            + "<gridsquare:4>FN42 "
            + "<mode:3>FT8 "
            + "<rst_sent:3>-08 "
            + "<rst_rcvd:3>-12 "
            + "<qso_date:8>20231114 "
            + "<time_on:6>221320 "
            + "<qso_date_off:8>20231114 "
            + "<time_off:6>221520 "
            + "<band:3>20m "
            + "<freq:6>14.074 "
            + "<station_callsign:5>K0XYZ "
            + "<my_gridsquare:4>EN37 "
            + "<comment:0> <eor>\n"
        XCTAssertEqual(Adif.export([r]), expected)
    }

    func testExportOmitsEmptyOptionalsButKeepsCallFlagsAndComment() {
        let out = Adif.export([rec(call: "W1AW")]) // all optionals empty
        XCTAssertEqual(out,
            "FT8AF ADIF Export<eoh>\n<call:4>W1AW <QSL_RCVD:1>N <comment:0> <eor>\n")
    }

    func testExportUsesUtf8ByteLengthForComment() {
        // "é" is 2 UTF-8 bytes; the length field must be byte count, not char count.
        let out = Adif.export([rec(call: "K1ABC", comment: "é")])
        XCTAssertTrue(out.contains("<comment:2>é "))
    }

    // MARK: round trip

    func testRoundTrip() {
        let r1 = rec(call: "K1ABC", gridsquare: "FN42", mode: "FT8", rstSent: "-08", rstRcvd: "-12",
                     qsoDate: "20231114", timeOn: "221320", band: "20m", freq: "14.074",
                     stationCallsign: "K0XYZ", myGridsquare: "EN37", comment: "GL")
        let r2 = rec(call: "W9XYZ", mode: "FT4")
        let parsed = Adif.parse(Adif.export([r1, r2]))
        XCTAssertEqual(parsed, [r1, r2]) // ids both nil; absent optionals parse back as ""
    }

    // MARK: parse

    func testParseIgnoresHeaderAndUnknownFields() {
        let adif =
            "Generated by WSJT-X\n<adif_ver:5>3.1.0 <programid:6>WSJT-X <eoh>\n"
            + "<call:5>K1ABC <qsl_rcvd:1>N <gridsquare:4>FN42 <mode:3>FT8 <foo:3>bar <eor>\n"
        let parsed = Adif.parse(adif)
        XCTAssertEqual(parsed.count, 1)
        XCTAssertEqual(parsed[0].call, "K1ABC")
        XCTAssertEqual(parsed[0].gridsquare, "FN42")
        XCTAssertEqual(parsed[0].mode, "FT8")
    }

    func testParseValueContainingAngleBrackets() {
        // Length-prefixed: the inner < and > in the comment are data, not tags.
        let parsed = Adif.parse("<eoh>\n<call:5>K1ABC <comment:5>a<b>c <eor>\n")
        XCTAssertEqual(parsed.count, 1)
        XCTAssertEqual(parsed[0].call, "K1ABC")
        XCTAssertEqual(parsed[0].comment, "a<b>c")
    }

    func testParseIsCaseInsensitive() {
        let parsed = Adif.parse("<EOH>\n<CALL:5>K1ABC <Mode:3>FT8 <EOR>")
        XCTAssertEqual(parsed.count, 1)
        XCTAssertEqual(parsed[0].call, "K1ABC")
        XCTAssertEqual(parsed[0].mode, "FT8")
    }

    func testParseFieldWithTypeIndicator() {
        let parsed = Adif.parse("<eoh>\n<call:5>K1ABC <freq:6:N>14.074 <eor>")
        XCTAssertEqual(parsed[0].freq, "14.074")
    }

    func testParseHeaderlessMultipleRecords() {
        let parsed = Adif.parse("<call:5>K1ABC <eor>\n<call:5>W9XYZ <mode:3>FT8 <eor>\n")
        XCTAssertEqual(parsed.map { $0.call }, ["K1ABC", "W9XYZ"])
        XCTAssertEqual(parsed[1].mode, "FT8")
    }

    func testParseTrailingRecordWithoutEor() {
        let parsed = Adif.parse("<eoh>\n<call:5>K1ABC <mode:3>FT8 ")
        XCTAssertEqual(parsed.count, 1)
        XCTAssertEqual(parsed[0].call, "K1ABC")
    }

    func testParseEmptyOrHeaderOnly() {
        XCTAssertTrue(Adif.parse("").isEmpty)
        XCTAssertTrue(Adif.parse("FT8AF ADIF Export<eoh>\n").isEmpty)
    }

    func testParseDropsRecordsWithoutCall() {
        // First record has only QSL/unknown fields (no CALL) -> dropped; second is kept.
        let parsed = Adif.parse("<eoh>\n<qsl_rcvd:1>N <foo:3>bar <eor>\n<call:5>K1ABC <eor>\n")
        XCTAssertEqual(parsed.map { $0.call }, ["K1ABC"])
    }

    func testParseDropsEmptyCallRecord() {
        // An explicit but empty <call:0> is not a valid QSO either.
        XCTAssertTrue(Adif.parse("<eoh>\n<call:0> <mode:3>FT8 <eor>").isEmpty)
    }

    func testParseSkipsMalformedOverLongField() {
        // Claims 99 bytes but only a few follow -> field skipped, record still parses call.
        let parsed = Adif.parse("<eoh>\n<call:5>K1ABC <comment:99>oops <eor>")
        XCTAssertEqual(parsed.count, 1)
        XCTAssertEqual(parsed[0].call, "K1ABC")
        XCTAssertEqual(parsed[0].comment, "")
    }

    func testParseSkipsHugeFieldLengthWithoutOverflowTrap() {
        // A field length near Int.max fits in Int (so it parses) but is far longer
        // than the remaining bytes. The over-long guard must reject it WITHOUT
        // evaluating `i + len` (which would trap on 64-bit signed overflow and
        // crash the whole app on import of a corrupt/hostile .adi). The record's
        // valid CALL is still parsed; the huge field is skipped like any other
        // over-long field.
        let huge = String(Int.max) // 9223372036854775807
        let parsed = Adif.parse("<eoh>\n<call:5>K1ABC <comment:\(huge)>x <eor>")
        XCTAssertEqual(parsed.count, 1)
        XCTAssertEqual(parsed[0].call, "K1ABC")
        XCTAssertEqual(parsed[0].comment, "")
    }
}
